#define HostName                       "Arizona RP | Parviz"
#define State_Names 				   "Arizona"
#define Mode_City					   "Test"
#define ServerNumber                   0
#define Server_Password                ""
#define DB_host                        "127.0.0.1"
#define DB_user                        "user"
#define DB_database                    "database"
#define DB_password                    "password"